import "./globals.css";
import { main } from "../utils/fonts";
import Navbar from "@/components/nav/navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={main.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
